export enum CandlePattern {
  RRRRR = 'RRRRR',
  RRRRG = 'RRRRG',
  RRRGR = 'RRRGR',
  RRRGG = 'RRRGG',
  RRGRR = 'RRGRR',
  RRGRG = 'RRGRG',
  RRGGR = 'RRGGR',
  RRGGG = 'RRGGG',
  RGRRR = 'RGRRR',
  RGRRG = 'RGRRG',
  RGRGR = 'RGRGR',
  RGRGG = 'RGRGG',
  RGGRR = 'RGGRR',
  RGGRG = 'RGGRG',
  RGGGR = 'RGGGR',
  RGGGG = 'RGGGG',
  GRRRR = 'GRRRR',
  GRRRG = 'GRRRG',
  GRRGR = 'GRRGR',
  GRRGG = 'GRRGG',
  GRGRR = 'GRGRR',
  GRGRG = 'GRGRG',
  GRGGR = 'GRGGR',
  GRGGG = 'GRGGG',
  GGRRR = 'GGRRR',
  GGRRG = 'GGRRG',
  GGRGR = 'GGRGR',
  GGRGG = 'GGRGG',
  GGGRR = 'GGGRR',
  GGGRG = 'GGGRG',
  GGGGR = 'GGGGR',
  GGGGG = 'GGGGG',
}

export enum UptrendPatterns {
  RRGGG = 'RRGGG',
  RGRGG = 'RGRGG',
  RGGRG = 'RGGRG',
  RGGGR = 'RGGGR',
  GRRGG = 'GRRGG',
  GRGRG = 'GRGRG',
  GRGGR = 'GRGGR',
  GGRRG = 'GGRRG',
  GGRGR = 'GGRGR',
  GGGRR = 'GGGRR',
  RGGGG = 'RGGGG',
  GRGGG = 'GRGGG',
  GGRGG = 'GGRGG',
  GGGRG = 'GGGRG',
  GGGGR = 'GGGGR',
  GGGGG = 'GGGGG',
}

export enum DowntrendPatterns {
  RRRRR = 'RRRRR',
  RRRRG = 'RRRRG',
  RRRGR = 'RRRGR',
  RRRGG = 'RRRGG',
  RRGRR = 'RRGRR',
  RRGRG = 'RRGRG',
  RRGGR = 'RRGGR',
  RGRRR = 'RGRRR',
  RGRRG = 'RGRRG',
  RGRGR = 'RGRGR',
  RGGRR = 'RGGRR',
  GRRRR = 'GRRRR',
  GRRRG = 'GRRRG',
  GRRGR = 'GRRGR',
  GRGRR = 'GRGRR',
  GGRRR = 'GGRRR',
}